### ISSUE TITLE
Select MSP messages to add

### ISSUE THREAD

**Issue by PepMS** [BonaDrone/Hackflight#1]
From all available messages available in MSP, select the ones with a higher priority to implement.

**Comment by PepMS** [comment]
Test Comment

**Comment by PepMS** [comment]
## Existing Requests:
MSP_RAW_IMU (102): raw values for the IMU 9250.
MSP_ATTITUDE (108): roll, pitch, yaw values.
MSP_ALTITUDE (109): Altitude estimation and vertical velocity.
MSP_ANALOG (110): Power/battery data

##  Existing Commands:
MSP_SET_RAW_RC (200): inject RC channel via MSP. Useful to command the quad via UART.
MSP_SET_PID (202): Set PID constants from the GCS.
MSP_ACC_CALIBRATION (205): We will need an accelerometer calibration routine.
MSP_MAG_CALIBRATION (206): We will need a magnetometer calibration routine.
MSP_SET_MOTOR (214): To set individual Motor. Useful to test individual motor from the GCS.

## New Requests:
MSP_WP: get x,y,z,yaw waypoint for indoor navigation w.r.t. the arming state.

## New Commands:
MSP_SET_WP: set x,y,z,yaw waypoint for indoor navigation w.r.t. the arming state.

**Comment by simondlevy** [comment]
MSP_ARM/DISARM implemented today as MPS_SET_ARM (true/false)

**Comment by simondlevy** [comment]
Just a reminder: it's very easy to add new MSP messages to Hackflight:

(1) Edit [messages.json](https://github.com/simondlevy/Hackflight/blob/master/extras/parser/messages.json)

(2) Run [msppg.py](https://github.com/simondlevy/Hackflight/blob/master/extras/parser/msppg.py).  This will auto-generate a new [mspparser.hpp](https://github.com/simondlevy/Hackflight/blob/master/src/mspparser.hpp) in the firmware source

(3) Add virtual-method implementation(s) to hackflight.hpp, as shown [here](https://github.com/simondlevy/Hackflight/blob/master/src/hackflight.hpp#L260-L283)
