### ISSUE TITLE
Pass the HackFlight object via pointer to the MSP class

### ISSUE THREAD

**Issue by PepMS** [BonaDrone/Hackflight#13]
A lot of messages sent through MSP are related to the state of the HackFlight. A lot of times we end up passing variables of the HackFlight class.

In order to avoid a lot of parameters in functions like the one in the link
https://github.com/BonaDrone/Hackflight/blob/4aaffef61a64ff761e2ce05e579f296ae3b10774/src/boards/msp.hpp#L162
would be useful to pass a pointer to the class intead of all the parameters.

We have to be carefull in accessing the info of the class.

**Comment by simondlevy** [comment]
Completed and tested today.

**Comment by juangallostra** [comment]
Closing as per @simondlevy 's comment
