### ISSUE TITLE
Command MSP_emergency_land

### ISSUE THREAD

**Issue by acazorso7** [BonaDrone/Hackflight#87]
## Feature / Bug description
An emergency MSP command must be implemented in order to land the drone if it's executed.

Code = 226

## Expected behavior
The drone will land with prio 1 if the command it's executed.

**Comment by juangallostra** [comment]
@acazorso7  The code 226 is currently used for the LOST_SIGNAL message when the WiFi socket is disconnected. Although the functionality is not yet active, it might be a good idea to keep the code 226 for this message. Maybe we can use code = 229?
