### ISSUE TITLE
MSP_ARM implementation

### ISSUE THREAD

**Issue by PepMS** [BonaDrone/Hackflight#9]
We want to implement a message to arm the copter. This will probably imply the following changes to the code:

- Make a method inside the class "Hackflight" that calling imply the safetycheck and the arming in the event of passing this safety check.

**Comment by PepMS** [comment]
Added with command number 216

**Comment by juangallostra** [comment]
Relevant commit: 6a59eaba26869a1ff34b9ae28d966ac96d3fd496

**Comment by juangallostra** [comment]
Arming via MSP is already supported. See:

https://github.com/simondlevy/Hackflight/blob/c064eedec650e0eff8ef046790bdd581797839d9/src/msp.hpp#L40

and

https://github.com/simondlevy/Hackflight/commit/bf9e492a062b80c90fe791f7dd8e414e2b06d78c
